import type { Metadata } from "next";
import { Anta, Inter } from "next/font/google";


import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import './globals.css'; // Your existing styles



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const anta = Anta({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-anta",
});

export const metadata: Metadata = {
  title: "Team Matchmaking App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${anta.variable} d-flex flex-column min-vh-100`}>
        <Navbar />
        <main className="flex-grow-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
